language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - cd uthando
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require uthando-cms/uthando-dompdf:dev-master
  - php composer.phar install

script:
  - cd vendor/uthando-cms/uthando-dompdf/test
  - phpunit
