language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - cd uthando
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar -n --update-no-dev require dompdf/dompdf:0.6.*
  - cp -R ../uthando-dompdf ./module/UthandoDomPdf

script:
  - cd module/UthandoDomPdf/test
  - phpunit
