language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - cd uthando
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-dev
  - php composer.phar require --update-no-dev dompdf/dompdf:0.6.*
  - php composer.phar require --update-no-dev uthando-cms/uthando-common:1.*
  - cp -R ../uthando-dompdf ./module/UthandoDomPdf

script:
  - cd module/UthandoDomPdf/test
  - phpunit
