language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - cd uthando
  - curl -s http://getcomposer.org/installer | php
  - cp ../uthando-dompdf/composer.json ./
  - php composer.phar -n --no-dev install
  - cp -R ../uthando-dompdf ./module/UthandoDomPdf

script:
  - cd module/UthandoDomPdf/test
  - phpunit
